"""etf lookthrough tables

Revision ID: 0d899d04697c
Revises: 94be4b2ff7e1
Create Date: 2026-07-18 00:08:54.820554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d899d04697c'
down_revision: Union[str, None] = '94be4b2ff7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etf_holdings',
    sa.Column('etf_code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('etf_code', 'date', 'stock_code')
    )
    op.create_table('etf_stats',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('aum', sa.BigInteger(), nullable=True),
    sa.Column('net_inflow', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_table('flow_path',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('direct_net', sa.BigInteger(), nullable=True),
    sa.Column('via_etf_net', sa.BigInteger(), nullable=True),
    sa.Column('top_etfs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_table('flow_rank',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('investor', sa.String(length=30), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('net_value', sa.BigInteger(), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'investor', 'rank')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flow_rank')
    op.drop_table('flow_path')
    op.drop_table('etf_stats')
    op.drop_table('etf_holdings')
    # ### end Alembic commands ###
