"""scalp_pick table

Revision ID: 1fbf949fc666
Revises: dcdb233e5430
Create Date: 2026-07-21 10:36:26.927989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fbf949fc666'
down_revision: Union[str, None] = 'dcdb233e5430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scalp_pick',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_rank', sa.SmallInteger(), nullable=True),
    sa.Column('entry_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('entry_change_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('entry_turnover', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('in_attention_top_at_entry', sa.Boolean(), nullable=False),
    sa.Column('change_rate_5m', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('change_rate_15m', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('change_rate_30m', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('change_rate_60m', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('change_rate_eod', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('date', 'code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scalp_pick')
    # ### end Alembic commands ###
