"""restore flow_rank is_etf, drop stray group_snapshot is_etf

Revision ID: 2b5430790c7e
Revises: 50b6c21440a4
Create Date: 2026-07-18 02:20:21.784120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5430790c7e'
down_revision: Union[str, None] = '50b6c21440a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 50b6c21440a4가 모델 편집 실수(is_etf 필드가 GroupSnapshot으로 밀림)로
    # flow_rank.is_etf를 드롭해 태깅 데이터가 유실됐다. 컬럼을 복구하고 기존 행은
    # stocks 마스터(is_etf=true인 ETF 300종목 적재됨)로 재태깅한다.
    op.add_column(
        'flow_rank',
        sa.Column('is_etf', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.execute(
        "UPDATE flow_rank SET is_etf = TRUE"
        " WHERE code IN (SELECT code FROM stocks WHERE is_etf)"
    )
    op.drop_column('group_snapshot', 'is_etf')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_snapshot', sa.Column('is_etf', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('flow_rank', 'is_etf')
    # ### end Alembic commands ###
