"""value_rank group_snapshot flow_rank market

Revision ID: 50b6c21440a4
Revises: 8e2fcaf84e67
Create Date: 2026-07-18 02:18:47.990798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b6c21440a4'
down_revision: Union[str, None] = '8e2fcaf84e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_snapshot',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('group_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('change_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('market_sum', sa.BigInteger(), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'group_type', 'name')
    )
    op.create_table('value_rank',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('change_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=False),
    sa.Column('turnover', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('date', 'market', 'rank')
    )
    op.add_column('flow_rank', sa.Column('market', sa.String(length=10), nullable=True))
    op.drop_column('flow_rank', 'is_etf')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_rank', sa.Column('is_etf', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('flow_rank', 'market')
    op.drop_table('value_rank')
    op.drop_table('group_snapshot')
    # ### end Alembic commands ###
