"""initial schema

Revision ID: 94be4b2ff7e1
Revises: 
Create Date: 2026-07-15 16:12:59.872269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94be4b2ff7e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect_log',
    sa.Column('job', sa.String(length=50), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('rows', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job', 'target_date')
    )
    op.create_table('index_ohlcv',
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('market', 'date')
    )
    op.create_table('macro_series',
    sa.Column('series', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('series', 'date')
    )
    op.create_table('market_flow',
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('investor', sa.String(length=30), nullable=False),
    sa.Column('net_value', sa.BigInteger(), nullable=True),
    sa.Column('net_volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('market', 'date', 'investor')
    )
    op.create_table('stocks',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('is_etf', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('program_trade',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('arb_net', sa.BigInteger(), nullable=True),
    sa.Column('non_arb_net', sa.BigInteger(), nullable=True),
    sa.Column('total_net', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_table('stock_flow',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('investor', sa.String(length=30), nullable=False),
    sa.Column('net_value', sa.BigInteger(), nullable=True),
    sa.Column('net_volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('code', 'date', 'investor')
    )
    op.create_table('stock_ohlcv',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.BigInteger(), nullable=True),
    sa.Column('high', sa.BigInteger(), nullable=True),
    sa.Column('low', sa.BigInteger(), nullable=True),
    sa.Column('close', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    op.create_table('watchlist',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('whale_score',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('code', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whale_score')
    op.drop_table('watchlist')
    op.drop_table('stock_ohlcv')
    op.drop_table('stock_flow')
    op.drop_table('program_trade')
    op.drop_table('stocks')
    op.drop_table('market_flow')
    op.drop_table('macro_series')
    op.drop_table('index_ohlcv')
    op.drop_table('collect_log')
    # ### end Alembic commands ###
