"""intraday_sample table

Revision ID: a22f6b66dffe
Revises: 1fbf949fc666
Create Date: 2026-07-22 12:20:41.703312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22f6b66dffe'
down_revision: Union[str, None] = '1fbf949fc666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intraday_sample',
    sa.Column('series_key', sa.String(length=50), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('resolution_seconds', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('series_key', 'time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intraday_sample')
    # ### end Alembic commands ###
