"""market_breadth table

Revision ID: dcdb233e5430
Revises: 2b5430790c7e
Create Date: 2026-07-18 02:24:24.123249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdb233e5430'
down_revision: Union[str, None] = '2b5430790c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_breadth',
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('adv', sa.SmallInteger(), nullable=True),
    sa.Column('dec', sa.SmallInteger(), nullable=True),
    sa.Column('flat', sa.SmallInteger(), nullable=True),
    sa.Column('limit_up', sa.SmallInteger(), nullable=True),
    sa.Column('limit_down', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('market', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_breadth')
    # ### end Alembic commands ###
